name: say_hello
on: 
  issues:
    types: [opened, reopened]
jobs:
  job_name: 
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: echo
        run: echo "Hello, world"
      - name: logs
     # number, title, body, assignees, and labels 
        run: |
            echo "Issue Number: ${ISSUE_NUMBER}"
            echo "Issue Title: ${ISSUE_TITLE}"
            echo "Issue Body: ${ISSUE_BODY}"
            echo "Issue Assignees: ${ISSUE_ASSIGNEES}"
            echo "Issue Labels: ${ISSUE_LABELS}"
        env:
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            ISSUE_TITLE: ${{ github.event.issue.title }}
            ISSUE_BODY: ${{ github.event.issue.body }}
            ISSUE_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login, ', ') }}
            ISSUE_LABELS: ${{ join(github.event.issue.labels.*.name, ', ') }}
      - name: Generate Code with ChatGPT
        if: github.event.issue.labels == 'autocoder-bot'
        id: generate_code
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            REPOSITORY: ${{github.repository}}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        run:
            chmod +x scripts/script.sh
            scripts/script.sh ${GITHUB_TOKEN} ${REPOSITORY} ${ISSUE_NUMBER} ${OPENAI_API_KEY} > autocoder-artifact
            # action to upload an artifact
            # params:
              # inputs
              # inputs
            ls
