on:
  issues:
    types:
      - opened
      - reopened
jobs:
  access_issue_info:
    runs-on: ubuntu-latest

    steps:
      - name: Print Issue Information
     # number, title, body, assignees, and labels 
        run: |
            echo "Issue Number: ${ISSUE_NUMBER}"
            Issue Number: ${{ github.event.issue.number }}
            echo "Issue Title: ${ISSUE_TITLE}"
            Issue Number: ${{ github.event.issue.title }}
            echo "Issue Body: ${ISSUE_BODY}
            Issue Body: ${{ github.event.issue.body }}
            echo "Issue Assignees: ${ISSUE_ASSIGNEES}
            Issue Assignees: ${{ join(github.event.issue.assignees.*.login, ', ') }}
            echo "Issue Labels: ${ISSUE_LABELS}
            Issue Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}

      
